rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: credits_clean
  publisher:
    - type: direct
      queue: movies_cast_joined
  base_db:
    - type: broadcast
      queue: argentina_post_2000_cast
      exchange: argentina_post_2000
healthcheck:
  port: 13434
log:
  level: INFO
