rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: ratings_clean
  publisher:
    - type: direct
      queue: movies_rating_joined
  base_db: argentina_post_2000

log:
  level: INFO
