name: tpEscalabilidad
services:
  rabbitmq:
    container_name: rabbitmq
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq.conf
      # User and pass config
      # - RABBITMQ_DEFAULT_USER=user
      # - RABBITMQ_DEFAULT_PASS=password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - testing_net

  client:
    container_name: client
    build:
      context: .
      dockerfile: src/client/Dockerfile
    command:
      [
        "python",
        "src/client/main.py",
        ".data/movies_metadata.csv",
        ".data/ratings.csv",
        ".data/credits.csv",
      ]
    image: client:latest
    environment:
      - SERVER_HOST=cleaner
      - SERVER_PORT=12345
      - BATCH_SIZE_MOVIES=20
      - BATCH_SIZE_RATINGS=100
      - BATCH_SIZE_CREDITS=20
      - PYTHONPATH=/app
    networks:
      - testing_net
    volumes:
      - ./.data:/app/.data
    depends_on:
      cleaner:
        condition: service_started

  cleaner:
    container_name: cleaner
    build:
      context: .
      dockerfile: src/server/Dockerfile
    command: ["python", "src/server/cleaner/main.py"]
    environment:
      - PYTHONUNBUFFERED=1
      - SERVER_PORT=12345
      - LISTENING_BACKLOG=3
      - BATCH_SIZE_MOVIES=20
      - BATCH_SIZE_RATINGS=100
      - BATCH_SIZE_CREDITS=20
      - RABBIT_HOST=rabbitmq
      - MOVIES_CLEANED_QUEUE=movies_cleaned_queue
      - CREDITS_CLEANED_QUEUE=credits_cleaned_queue
      - PYTHONPATH=/app
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  filter_single_country:
    container_name: filter_single_country
    build:
      context: .
      dockerfile: src/server/Dockerfile
    command: ["python", "src/server/filters/main.py", "solo_country"]
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbitmq
      - INPUT_QUEUE=movies_cleaned_queue
      - OUTPUT_QUEUE=movies_single_country_queue
      - PYTHONPATH=/app
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
    # deploy:
    #   replicas: 3

  country_budget_counter:
    container_name: country_budget_counter
    build:
      context: .
      dockerfile: src/server/Dockerfile
    command: ["python", "src/server/counters/main.py", "country_budget"]
    environment:
      - PYTHONUNBUFFERED=1
      - RABBIT_HOST=rabbitmq
      - INPUT_QUEUE=movies_single_country_queue
      - PYTHONPATH=/app
    networks:
      - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
