# Scale all scalable nodes equally
all: 2

# Clients
clients: 2

# Filters
filter_single_country: 2
filter_budget_revenue: 2
filter_post_2000: 2
filter_argentina: 2
filter_argentina_and_spain: 2
filter_decade_00: 2

# Counters
rating_counter: 2
country_budget_counter: 2
actor_counter: 2

# Joiners

ratings_joiner: 2
cast_joiner: 2

# Others
cast_splitter: 1
sentiment_analyzer: 2

# Watcher
watcher: 3
