rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: movies_rating_joined
  publisher:
    - type: direct
      queue: movies_rating_counted
healthcheck:
  port: 13434
log:
  level: INFO
