rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: movie_budget_revenue_clean
  publisher:
    - type: direct
      queue: sentiment_analyzed
heartbeat:
  server_port: 13434
  client_port: 13434
log:
  level: INFO
