rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: broadcast
      exchange: movies_metadata_clean
      queue: movies_metadata_clean_sentiment_analyzed
  publisher:
    - type: direct
      queue: sentiment_analyzed
log:
  level: INFO
