rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: broadcast
      queue: post_2000_argentina_and_spain_filter
      exchange: post_2000
  publisher:
    - type: direct
      queue: argentina_and_spain
log:
  level: INFO
