rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: broadcast
      queue: post_2000_argentina_filter
      exchange: post_2000
  publisher:
    - type: broadcast
      exchange: argentina_post_2000
healthcheck:
  port: 13434
log:
  level: INFO
