rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: argentina_and_spain
  publisher:
    - type: direct
      queue: decade_00
healthcheck:
  port: 13434
log:
  level: INFO
