rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: broadcast
      queue: movies_metadata_clean_post_2000
      exchange: movies_metadata_clean
  publisher:
    - type: broadcast
      exchange: post_2000
log:
  level: INFO
