rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: broadcast
      exchange: movies_metadata_clean
      queue: movies_metadata_clean_solo_country
  publisher:
    - type: direct
      queue: solo_country
healthcheck:
  port: 13434
log:
  level: INFO
