rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: broadcast
      queue: movies_metadata_clean
  publisher:
    - type: direct
      queue: solo_country
log:
  level: INFO

replication:
  enabled: true
  port: 6000
  peers:
    - "filter_single_country-1:6000"
    - "filter_single_country-2:6000"
