rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: report
  publisher:
    - type: broadcast
      queue: movies_metadata_clean
      msg_type: Movie
log:
  level: ERROR
