rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: reporter
  publisher:
    - type: broadcast
      exchange: movies_metadata_clean
      msg_type: Movie
    - type: direct
      queue: ratings_clean
      msg_type: Rating
    - type: direct
      queue: credits_clean
      msg_type: Cast
heartbeat:
  port: 13434
log:
  level: INFO
