rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: movies_rating_counted
  publisher:
    - type: direct
      queue: reporter
heartbeat:
  port: 13434
log:
  level: INFO
