rabbit:
  host: rabbitmq
connection:
  consumer:
    - type: direct
      queue: sentiment_analyzed
  publisher:
    - type: direct
      queue: reporter
healthcheck:
  port: 13434
log:
  level: INFO
