# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/casts.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'protobuf/casts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protobuf/casts.proto\x12\x08protobuf\" \n\x04\x43\x61st\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04\x63\x61st\x18\x02 \x03(\t\"%\n\x05\x43\x61sts\x12\x1c\n\x04list\x18\x01 \x03(\x0b\x32\x0e.protobuf.CastB\x05\x92\x03\x02\x08\x01\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.casts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\222\003\002\010\001'
  _globals['_CAST']._serialized_start=34
  _globals['_CAST']._serialized_end=66
  _globals['_CASTS']._serialized_start=68
  _globals['_CASTS']._serialized_end=105
# @@protoc_insertion_point(module_scope)
