# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/movie_budget_counter.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 2, '', 'protobuf/movie_budget_counter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#protobuf/movie_budget_counter.proto\x12\x08protobuf";\n\x12MovieBudgetCounter\x12\x0f\n\x07\x63ountry\x18\x01 \x01(\t\x12\x14\n\x0ctotal_budget\x18\x02 \x01(\x04"A\n\x13MovieBudgetCounters\x12*\n\x04list\x18\x01 \x03(\x0b\x32\x1c.protobuf.MovieBudgetCounterB\x05\x92\x03\x02\x08\x01\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'protobuf.movie_budget_counter_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\222\003\002\010\001'
    _globals['_MOVIEBUDGETCOUNTER']._serialized_start = 49
    _globals['_MOVIEBUDGETCOUNTER']._serialized_end = 108
    _globals['_MOVIEBUDGETCOUNTERS']._serialized_start = 110
    _globals['_MOVIEBUDGETCOUNTERS']._serialized_end = 175
# @@protoc_insertion_point(module_scope)
