# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/movies.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 2, '', 'protobuf/movies.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15protobuf/movies.proto\x12\x08protobuf"\x99\x01\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06genres\x18\x03 \x03(\t\x12\x14\n\x0crelease_date\x18\x04 \x01(\t\x12\x1c\n\x14production_countries\x18\x05 \x03(\t\x12\x0e\n\x06\x62udget\x18\x06 \x01(\x05\x12\x0f\n\x07revenue\x18\x07 \x01(\x05\x12\x10\n\x08overview\x18\x08 \x01(\t"\'\n\x06Movies\x12\x1d\n\x04list\x18\x01 \x03(\x0b\x32\x0f.protobuf.MovieB\x05\x92\x03\x02\x08\x01\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.movies_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\222\003\002\010\001'
    _globals['_MOVIE']._serialized_start = 36
    _globals['_MOVIE']._serialized_end = 189
    _globals['_MOVIES']._serialized_start = 191
    _globals['_MOVIES']._serialized_end = 230
# @@protoc_insertion_point(module_scope)
