# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/movie_avg_budgets.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 2, '', 'protobuf/movie_avg_budgets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n protobuf/movie_avg_budgets.proto\x12\x08protobuf"4\n\x0eMovieAvgBudget\x12\x10\n\x08positive\x18\x01 \x01(\x02\x12\x10\n\x08negative\x18\x02 \x01(\x02\x42\x05\x92\x03\x02\x08\x01\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'protobuf.movie_avg_budgets_pb2', _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals['DESCRIPTOR']._loaded_options = None
    _globals['DESCRIPTOR']._serialized_options = b'\222\003\002\010\001'
    _globals['_MOVIEAVGBUDGET']._serialized_start = 46
    _globals['_MOVIEAVGBUDGET']._serialized_end = 98
# @@protoc_insertion_point(module_scope)
