# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/movie_ratings_avgs.proto
# Protobuf Python Version: 6.30.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    2,
    '',
    'protobuf/movie_ratings_avgs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protobuf/movie_ratings_avgs.proto\x12\x08protobuf\"C\n\x0eMovieRatingAvg\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x16\n\x0e\x61verage_rating\x18\x03 \x01(\x02\"9\n\x0fMovieRatingAvgs\x12&\n\x04list\x18\x01 \x03(\x0b\x32\x18.protobuf.MovieRatingAvgB\x05\x92\x03\x02\x08\x01\x62\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.movie_ratings_avgs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\222\003\002\010\001'
  _globals['_MOVIERATINGAVG']._serialized_start=47
  _globals['_MOVIERATINGAVG']._serialized_end=114
  _globals['_MOVIERATINGAVGS']._serialized_start=116
  _globals['_MOVIERATINGAVGS']._serialized_end=173
# @@protoc_insertion_point(module_scope)
